project:
  type: website
  output-dir: docs

website:
  title: "EIP Operations Website"
  navbar:
    right:
      - text: "Home"
        href: main.qmd
      - text: "Prior Staff"
        href: prior_staff.qmd

format:
  html:
    theme:
      light: spacelab
      dark: darkly
    css: styles.css
    toc: true



